name: Test Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Get commit history range
        id: commits
        run: echo "commit_range=$(git rev-parse --is-inside-work-tree && (git rev-list --count HEAD | grep -q '^[0-9]\+$' && echo HEAD~$(git rev-list --count HEAD) || echo HEAD~1))" >> $GITHUB_ENV

      - name: Lint commits
        run: npx commitlint --from=${{ env.commit_range }} --to=HEAD

      - name: Run linter
        run: npm run lint

      - name: Run tests with coverage
        run: npm run coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-coverage
